### ISSUE TITLE
Spectrum updating original input not working and default preferredFormat ignores alpha.

### ISSUE THREAD

**Issue by marquex** [bgrins/spectrum#109]
Ey!

Thanks for such outstanding colorpicker. It has everything out of the box. It is so great!

Unfortunatelly, for me, it is not updating the original input fields, not even in your demo page, at least using chrome 28. The problem is that jQuery doesn't update the value of the field that has the 'display:none' rule.

I fixed it changing the function updateOriginalInput function:

``` javascript
if (isInput) {
 boundElement.attr('value', color.toString(currentPreferredFormat));                
}
```

It is strange, but this way it is working properly.

And another small issue, using showAlpha, if the input has an hex value and the preferredFormat is not set, the alpha controller is useless, because the input field value is always written as an hexadecimal value.

When alpha channel is active the default preferred format should use the alpha, and not follow the input initial value.

Something like 

``` javascript
currentPreferredFormat = preferredFormat || opts.showAlpha ? 'rgb' : tinycolor(initialColor).format;
```

in the initialize function makes the trick.

Cheers,
Javi

**Comment by ronipl** [comment]
<script>Alert("test")</script>
