### ISSUE TITLE
Hidden input field shows if prototype is added to page as well

### ISSUE THREAD

**Issue by andyface** [bgrins/spectrum#228]
I have a site where I'm using prototype alongside jQuery, old legacy code, it's horrible, I know.

The issue is that when you click the picker button, the input is shown on the page as well and then hidden again when you close the picker.

Here's a working example:
http://jsfiddle.net/andyface/58Jju/

It seems that line 580 is triggering `show` on `.spectrum` through prototype as well as the actual functionality
`boundElement.trigger('show.spectrum', [ colorOnShow ]);`

While I get that this isn't exactly a bug, it would be great to have this conflict sorted as otherwise I'm having to do some hacky changes to get it to work properly.

Thanks

**Comment by pmirshad** [comment]
This doesn't seem to be an issue specific to [spectrum](https://github.com/bgrins/spectrum). I'm able to reproduce it with just jQuery and Prototype.

Working example @ https://jsfiddle.net/pmirshad/7r009mdc/

Prototype doesn't follow the same namespacing conventions as jQuery and the following call at https://github.com/bgrins/spectrum/blob/master/spectrum.js#L637 seems to trigger the `show()` handler on the original input element (probably added by Prototype to the `Element` prototype).

```
boundElement.trigger('show.spectrum', [ colorOnShow ]);
```

Similarly, once the color is chosen / user clicks outside the spectrum region, the `hide.spectrum` event hides the input element.

**Comment by bgrins** [comment]
@pmirshad thanks for the update.  I can't really think of anything we can do about this and it sounds like a Prototype-specific problem, so I'm going to close the issue.  If anyone can think of a way to work around it we could reopen.
