### ISSUE TITLE
Move event should be fired on any color update, change only when picker is closed with a color selected.  aka palette clicks should not fire change event

### ISSUE THREAD

**Issue by marcandre** [bgrins/spectrum#250]
Doc says about the `change` event:
> Called as the original input changes. Only happens when the input is closed or the 'Choose' button is clicked.

This is no longer true. For example clicking on a palette color will trigger `change`, and pressing `cancel` will revert the choice and trigger `change` again.

I believe the correct behavior for the `change` event should mimick HTML5 `<input type="color">` element, which is: everytime the swatch changes (even dragging around). Check it out here: http://jsfiddle.net/pceauodk/1/

1) I believe the doc should read:
> Called as the original input changes. Happens whenever a new color is set, e.g. by typing in a new value, clicking on the palette or dragging around the spectrum.

2) I think that the `set` method should be calling `updateOriginalInput`. Whenever you `set` a value, you have to update the original value.  Note: this removes the code smell of the API.

3)  Moreover, only `set` should be calling `updateOriginalInput`. For instance, in clickout I was wondering if the `updateOriginalInput` was really needed, and I think it doesn't do anything. At that point, the original input value is already updated.

4) Every `move` event should be followed by a `change` event, so `move` should be calling `set`. For this to make sense, `set` should exit early by comparing with the current input value, not with `get()`.

5) Consider deprecating the `move` event; I can't see a use for it now if the `change` event is triggered correctly.

Let me know if you'd like a PR

**Comment by bgrins** [comment]
This has now been fixed by #404 and #405 (code currently on master)

**Comment by amitzur** [comment]
wow, blast from the past :)
