### ISSUE TITLE
Non jquery version

### ISSUE THREAD

**Issue by RobertButera** [bgrins/spectrum#255]
Hi,

On the main page it states a non-jquery version of spectrum was created for use in devtools.  Is this port maintained anywhere.   I would be interested in using spectrum without jquery.

Rob

**Comment by sdhull** [comment]
For anyone else stumbling upon this issue and wondering where the Firefox link went, new location is:
https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/widgets/Spectrum.js

**Comment by asika32764** [comment]
For those who is looking for non-jQuery version, I forked a vanilla JS version here, please see: https://about.asika.tw/spectrum-vanilla/
