### ISSUE TITLE
click or tap on color rectangle does not move the reticle to the new color on devices which support both mouse and touch

### ISSUE THREAD

**Issue by GerHobbelt** [bgrins/spectrum#261]
Tested on: Asus laptop, Win8/64 with touchscreen and mouse support.

The tap behaviour to point&pick at a color from the sp_color color rectangle works on mouse-only devices, but not on modern machines like these.

---

Culprit is the draggable start() not invoking move() when the device has touch support which is an incorrect assumption: it doesn't matter if the device supports touch or not; when the color rectangle is tapped or receiving a touch/click-move/drag operation, the reticle should jump to the start position of such movement and track the movement; a tap/click is merely a no-distance-traveled move/drag in this sense.

**Comment by jordankomnick** [comment]
Hey, any word on this fix?  A project I'm working on is using Spectrum and we recently noticed this issue as well.

**Comment by bgrins** [comment]
Thanks for the PR, just merged it
