### ISSUE TITLE
'cancel' does not cancel after selecting from palette (clicking on a palette color fires the 'change' event)

### ISSUE THREAD

**Issue by Centurion** [bgrins/spectrum#269]
Hi,

when I open a color-picker, click on any color and then on 'cancel' instead of 'choose',
the color gets reset but the internal value stays on the last selected value; this is not good.
(I removed the display:none to see the rgb-values)

FF31, Ubuntu 14.04
Best,
Centurion

how to reproduce:
`<input name="tinta" id="css_1" value="rgb(0, 0, 0)" />`

```javascript
                $("#css_1").spectrum({
                    preferredFormat: "rgb"
                    ,showAlpha: true
                    ,showPalette: true
                    ,togglePaletteOnly: true
                 //   ,color: $(this).val() // spectrum tries to find the value, no need for explicit setting here
                    ,showSelectionPalette: true
                    ,localStorageKey: "spectrum.hydrogen"
                    ,maxSelectionSize: 9
                    ,showInitial: true
                });
```
initially the color-box is black, I open the spectrum-picker, click just for fun the yellow palette-entry and then on 'cancel' => the color-box gets resetted to black, but the value of "tinta" stays on rgb(255,255,0), thus seeing and commiting totally different things.

**Comment by LIDJungle** [comment]
I'm new to using Spectrum, and this is a major program breaker for me. :(

I'm using Spectrum to style text in Fabric.js. So, I have the "change" events hooked up to modify text. So, user selects a color from the palette, and the text changes color automatically from White to Purple. They click "Cancel" and Spectrum reverts to White, but their text is still Purple. So they go back to Spectrum and click White again, which is not seen as a change, so nothing happens. It's very confusing.

I changed the "cancel" text to "Close Colorpicker" - It's a bit less confusing.

In spectrum.js, line 465: updateOriginalInput(true);

By commenting this out, I no longer get change events when selecting from the palette. Is that going to break anything else? It seems to be working as God intended.

(And couldn't this be as easy as adding another option?)

    if (opts.paletteSelectFiresChange) {
        updateOriginalInput(true);
    }

Let me know if it's more complicated than that and I am causing stray bytes to flood the Antartic killing the baby seals.

I also notice that there's a "hideAfterPaletteSelect" - That would be option B. If palette select is always going to fire a change, might as well not give them the chance to cancel it. :)

Tried quite a few colorpickers yesterday, yours was easily the best. Thanks for the great work.

**Comment by bgrins** [comment]
> By commenting this out, I no longer get change events when selecting from the palette. Is that going to break anything else?

No, it shouldn't break anything and should work fine for your case.  It could be added as an option as you suggest, but there is another case where this happens - when setting from text input.  Both should be changed - I have a work in progress that cleans this up but just haven't been able to finish it up.  I'll take another shot at it and see if I can wrap it up.

**Comment by jaganreddy** [comment]
I faced same problem, ie when I click on cancel after selecting the color, new color is going to set to the text box. I am using v1.5.2 and I added a line 'boundElement.val(colorOnShow);' in revert() method in spectrum.js at line 665, its working great

**Comment by bgrins** [comment]
@Centurion @LIDJungle @jaganreddy OK, progress on this!  I believe I have a working set of changes in #405.

If any of you are able to do a test with the js file at the following link and let me know if it's working as you expect that would be super helpful feedback: https://raw.githubusercontent.com/bgrins/spectrum/palette-change/spectrum.js.

**Comment by bgrins** [comment]
Given no response I'm going to proceed with #405 and close this out
