### ISSUE TITLE
In Desktop Chrome browser while dragging, the popup closed if i dragstop outside the popup.

### ISSUE THREAD

**Issue by soundar24** [bgrins/spectrum#279]
Just open any sample in the Google Chrome browser, and open the color picker popup. Now drag the handle by pressing the mouse and move. The color values are changed continuously that is no problem. If i mouseup the handle from outside the popup then the popup closed immediately.

But it works fine in firefox browser.

**Comment by bgrins** [comment]
Thanks for reporting - we've noticed this in Issue #249.  I'm sure this used to work, but I went back and checked some older versions of the plugin against chrome and they all seem to have the same problem so I wonder if something changed with Chrome.  I've been experimenting with some changes over in that issue, so I'm going to close this as a duplicate
