### ISSUE TITLE
Input not focusable when hosted in Bootstrap Modal in Chrome/Firefox

### ISSUE THREAD

**Issue by dpen2000** [bgrins/spectrum#280]
1. Go to (in chrome/firefox): http://jsfiddle.net/52VtD/9841/
2. Click Launch Demo Modal
3.  Open color picker
4. Note showInput input element is not editable

It's not fully working in IE either: pressing enter when typing a color doesn't change the color; only clicking elsewhere in textbox works.

**Comment by dpen2000** [comment]
I've seen #276 and using appendTo: "parent" does get it working in Chrome/Firefox: but pressing enter key doesn't work.

**Comment by bgrins** [comment]
Doing `appendTo: $("#myModal")` seems to work for me in FF/Chrome: http://jsfiddle.net/52VtD/9846/.  Does this work for you?

**Comment by YacheLee** [comment]
Awesome. appendTo really save my whole day!!
I encounter the problem with modal bootstrap(http://getbootstrap.com/javascript/#modals)
Thank you.
