### ISSUE TITLE
feature request: hide on escape

### ISSUE THREAD

**Issue by nlac** [bgrins/spectrum#281]
Hi, i think it would be useful to provide a boolean param that enables to hide the widget on pressing escape. Of course, it is 2-3 lines of js to implement outside the widget but it would be practical to have it out-of-the-box.

**Comment by bgrins** [comment]
Hello, I agree this would be useful and should in fact be the default behavior

**Comment by bgrins** [comment]
Just landed this in master - on track for the 1.7 release

**Comment by bgrins** [comment]
This has been released in 1.7.0: https://github.com/bgrins/spectrum/releases/tag/1.7.0

**Comment by nlac** [comment]
cool! thx
