### ISSUE TITLE
SyntaxError: missing } after property list 

### ISSUE THREAD

**Issue by durangod** [bgrins/spectrum#287]
Its working great but i get this error on the console.  What am i missing thanks.. 

SyntaxError: missing } after property list 

here is how i set it up ( i have 5 inputs so i did it 5times with dif id's)

/* color picker */

    $("#colorpicker").spectrum({
        color: "#000000"
        showInput: true
    });

    $("#colorpicker2").spectrum({
        color: "#ffffff"
        showInput: true
    });

    $("#colorpicker3").spectrum({
        color: "#246893"
        showInput: true
    });

    $("#colorpicker4").spectrum({
        color: "#000000"
       showInput: true
    });

    $("#colorpicker5").spectrum({
        color: "#ffffff"
        showInput: true
    });

thanks

**Comment by durangod** [comment]
if i add the comma after the attribute like so

$("#colorpicker5").spectrum({
    color: "#ffffff",      
    showInput: true
});

it fixes the error but now the performance is horrible because it does not show the big color palette window like before.

**Comment by bgrins** [comment]
Hi, you will need the comma - the syntax error is in your example code.  See a working demo with a couple of examples here: http://jsfiddle.net/bgrins/ctkY3/.

**Comment by bgrins** [comment]
Closing the issue, but if you are seeing bad performance, please reopen and link to a test case so I can take a look at it.
