### ISSUE TITLE
Clicking on a palette color fires 'change' event

### ISSUE THREAD

**Issue by mazak** [bgrins/spectrum#289]
Clicking on a palette color fires 'change' event when I believe it shouldn't considering the specs:

> Called as the original input changes. Only happens when the input is closed or the 'Choose' button is clicked.

Here's a fiddle: http://jsfiddle.net/tffus29u/

Tested on Chrome and Firefox on osx.

**Comment by mazak** [comment]
To overcome this I do additional color save to the database on 'hide' as fortunately that event has the original color as the parameter.

**Comment by mattbierner** [comment]
This behavior also surprised me.

I ended up using local state and listening to the close button `click` event, which is fired after the `hide.spectrum` event here:

```
(function(){
    var pickedColor;
    $('.status-picker')
        .spectrum({
            showPalette: true,
            showSelectionPalette: true
        })
        .on('show.spectrum hide.spectrum', function(e, color) {
            pickedColor = color;
        });

    $('.sp-choose')
        .on('click', function() {
            performUpdate(pickedColor);
        });
}());
```

**Comment by bgrins** [comment]
Hi, I agree that this is bad behavior - clicking on a palette item should not fire the change event and should be revertable like when the color was picked via dragging.  Please follow #289, which covers the same thing.

**Comment by mazak** [comment]
This is #289. Did you mean other issue?

**Comment by mattkeys** [comment]
Ran into this quirk as well today. Is there another issue open for this already since this was closed previously and references this ticket as the 'other' ticket covering this issue?

**Comment by mattkeys** [comment]
My workaround for this:

using the 'hide' event as such:

hide: function(color) {
	// Check if color is null
	if ( color ) {
		color = color.toHexString();
	}
	// $colorpicker is my input element
	$colorpicker.trigger( 'color_change', color );
}

Then binding to the 'color_change' event with jQuery:

$(document).on( 'color_change', '.color_picker', function( event, color ) {
	console.log( color );
});

**Comment by bgrins** [comment]
> This is #289. Did you mean other issue?

Sorry!  I meant #250, specifically https://github.com/bgrins/spectrum/issues/250#issuecomment-66397975

**Comment by PeterVermont** [comment]
Be careful when using the hide event. It is called both when choosing 'cancel' (if you picker has that) and when clicking outside.

Luckily, in the cancel case the hide event receives the original color from before picker opening so setting your color won't actually change anything.
