### ISSUE TITLE
Modal dialog interaction - spectrums appear over modal dialog

### ISSUE THREAD

**Issue by golgistudio** [bgrins/spectrum#309]
When displaying a modal dialog, flat spectrums appear over the dialog.

Example:
http://codepen.io/LaurieReynolds/pen/qdWGZm
Scroll down until the text "Open Modal" appears

Expected behavior:  The modal dialog should appear on top of the spectrums

Browsers: IE, FireFox, Chrome

![image](https://cloud.githubusercontent.com/assets/5599690/7288852/9e03c1ce-e91c-11e4-87da-90d612a1d582.png)

**Comment by colinvella** [comment]
Try Adding the following to your CSS (after the inclusion of spectrum.css):
.sp-container {
  z-index: 1;
}

You may have to tweak z-index (some other value as long as it is < 99999 as per your modalDialog css).

**Comment by golgistudio** [comment]
Works great!   Thank you!
