### ISSUE TITLE
Is JQuery Required?

### ISSUE THREAD

**Issue by rjcarr** [bgrins/spectrum#312]
Looking at the main writeup here: 

    http://bgrins.github.io/spectrum/

The title is "the no hassle jquery color picker", and all of the examples include jquery, but at the bottom there are identical links to "javascript color picker", "jquery color picker", etc.  

Then in the devtools section you talk about removing a "jquery dependency".

Anyway, just curious because I really like what spectrum offers but my project doesn't use jquery.

Thanks!

(And sorry, I didn't know of a better way to ask a question without spamming your twitter account)

**Comment by bgrins** [comment]
Hi, thanks for the interest in the project.  See also #255, specifically https://github.com/bgrins/spectrum/issues/255#issuecomment-58209204.  Right now there isn't a version that has all the same features and doesn't rely on jQuery, but I've thought about changing it to make jQuery optional.  It would require reorganizing things in the project a fair amount, which I've been interested in doing but just haven't had the time to.

**Comment by rjcarr** [comment]
Thanks for the quick response!  Sorry I didn't see the previous question.  Thanks again for the tool.
