### ISSUE TITLE
JSFiddle Example Error

### ISSUE THREAD

**Issue by JamesMcFall** [bgrins/spectrum#313]
I just noted the JSFiddle example from your docs (at http://jsfiddle.net/bgrins/ctkY3/) doesn't work.

```
Uncaught TypeError: Cannot read property 'top' of undefined 
spectrum.js:985
```

Thought you'd like to know.

**Comment by bgrins** [comment]
Yikes, thanks for the heads up.   I know that was just working after the last update so I'm not sure what's changed.  I'll take a look

**Comment by bgrins** [comment]
Ah wow, looks like `offset` may have been broken in the jQuery (edge) version used in jsFiddle.  I've switched that to a stable version and things seem to be working again.  Let me know if you are seeing the issue still
