### ISSUE TITLE
spectrum color picker

### ISSUE THREAD

**Issue by bhargavi456** [bgrins/spectrum#317]
I have a spectrum color picker and another textbox . i want the textbox to change color instantaneously as the user moves the mouse around the spectrum color picker

**Comment by bcruddy** [comment]
Dragging across the color picker fires the `move.spectrum` event

    $(colorPickerSelector).on('move.spectrum', function (e, c) {
        console.log(c.toHexString());
    });

**Comment by bgrins** [comment]
@bcruddy thanks.  Yeah, this can be handled with the existing events.
