### ISSUE TITLE
When value is rgba

### ISSUE THREAD

**Issue by neotropic2023** [bgrins/spectrum#323]
I have a field with a default value of rgba(80,80,80,0.25), which could be random rgba. Used for styling box shadows. But spectum does not even register it. It defaults to rgb(0,0,0).

$("#caption-box-color").spectrum({preferredFormat: "rgb", showInitial: true, showInput: true, showAlpha: true});

After selecting and changing it to like rgba(0,0,0,0.50) it is saved as #000000?

**Comment by bgrins** [comment]
It seems to work fine for me in a demo like this: http://jsfiddle.net/2ageh2ox/1/.  Can you send over a failing test case?

**Comment by neotropic2023** [comment]
I was using type="color" not type="text" now it works. Thanks!

**Comment by neotropic2023** [comment]
One last ting....
input name="font-color" value="#936" id="font-color" class="form-control" type="color"
Shows as black. I see demo's using the 3 string color values.

**Comment by bgrins** [comment]
>  All my fields with 3 string color values show as black.

Yeah, that is defined by the spec: http://www.w3.org/TR/html-markup/input.color.html#input.color.attrs.value.  I'd recommend just using `text` inputs if you want to do anything more than 6 character hex values.

**Comment by neotropic2023** [comment]
Ok, I see. change them all to text and just gavce a class, then ran:

	$(".colors").each(function(){
		$(this).spectrum({
			color: $(this).val()
		});	
	});

Getting what I need, thanks.
