### ISSUE TITLE
Arabic language

### ISSUE THREAD

**Issue by code19** [bgrins/spectrum#324]
Choose: 
إختار
Cancel:
إلغاء

**Comment by code19** [comment]
// Spectrum Colorpicker
// Arabic (ar) localization
// https://github.com/bgrins/spectrum
(function ( $ ) {

    var localization = $.spectrum.localization["ar"] = {
        cancelText: "إلغاء",
        chooseText: "إختار",
        clearText: "إرجاع الألوان على ما كانت",
        noColorSelectedText: "لم تختار أي لون",
        togglePaletteMoreText: "أكثر",
        togglePaletteLessText: "أقل"
    };

    $.extend($.fn.spectrum.defaults, localization);

})( jQuery );

**Comment by bgrins** [comment]
Can you please create a pull request with a new `jquery.spectrum-ar.js` file?

**Comment by code19** [comment]
Done

**Comment by bgrins** [comment]
Fixed by https://github.com/bgrins/spectrum/pull/325
