### ISSUE TITLE
memory leak after calling destroy() on removing color picker with "flat" option from page

### ISSUE THREAD

**Issue by cathyandrobin** [bgrins/spectrum#344]
Using a color picker in a knockout component and adding and removing the component from the page shows a memory leak.  

The Spectrum destroy() function cleans up a lot but is leaving behind two listeners that are pinning a large number of detached DOM nodes. 

The call to spectrum destroy() happens on the KO dispose callback: 

			ko.utils.domNodeDisposal.addDisposeCallback(element, function () {
				$(element).spectrum('destroy');
			});

Adding the first two lines to the Spectrum destroy function below removes the leak: 

       function destroy() {
            $(doc).unbind("click.spectrum", clickout);
            $(window).unbind("resize.spectrum", resize);

            boundElement.show();
            offsetElement.unbind("click.spectrum touchstart.spectrum");
            container.remove();
            replacer.remove();
            spectrums[spect.id] = null;
        }

But it looks like the problem in is the hide() function, which unbinds the above listeners.   I tried calling hide() before destroy() to do the unbind() but, since I’m using the “flat” option,  the hide() function just returns and the unbind() call is never reached.  

I'll try to post a simplified test-case.

**Comment by bgrins** [comment]
Ah, thanks for the report.  Looks like there are 3 handlers that aren't being removed:

            $(doc).unbind("keydown.spectrum", onkeydown);
            $(doc).unbind("click.spectrum", clickout);
            $(window).unbind("resize.spectrum", resize);

All of these are called in hide() after the early return.  I think it'd be alright to move those three lines up above the early return.  And ideally have a test case in https://github.com/bgrins/spectrum/blob/master/test/tests.js to make sure that things are cleaned up properly.

Are you interested by any chance in making a PR for this?

**Comment by cathyandrobin** [comment]
Yes, I'll make the PR for it. 

Thanks!

**Comment by ncou** [comment]
any chance to get thoses changes in the official branche ?

Thank you.
