### ISSUE TITLE
Changing preferredFormat doesn't seem to do anything

### ISSUE THREAD

**Issue by eriqjaffe** [bgrins/spectrum#358]
I've got an application where I'd like to let the user choose their preferred color format - this has come from a specific request from a color-blind user that I'd like to accommodate.

I have a simple <select> so the user can choose their preferred format - it *appears* to change the format, but then when I click back on the spectrum selector, the color is still being shown in the default format.  I've created a fiddle here to demonstrate the issue:

[http://jsfiddle.net/mqmg7obb/1/](http://jsfiddle.net/mqmg7obb/1/)

**Comment by bgrins** [comment]
Yeah, looks like preferredFormat isn't supporting dynamic changes right now.  This could be added to applyOptions.

**Comment by bgrins** [comment]
This should be fixed now if you pull down master
