### ISSUE TITLE
Rotate the .alphaSlider 180 deg

### ISSUE THREAD

**Issue by Horray** [bgrins/spectrum#383]
I'm trying to rotate the `.alphaSlider` 180 deg. Of course I can do it with CSS (using `transform: rotate(180deg)`), but that's sort of a hack, and, there will anyway be other problems. I want to do it using the JavaScript source file.

How can I edit the source file so that I can rotate 180 Deg the `.alphaSlider`?

[Source: (Lines: 387-395)][3]

    draggable(alphaSlider, function (dragX, dragY, e) {
        currentAlpha = (dragX / alphaWidth);
        isEmpty = false;
        if (e.shiftKey) {
            currentAlpha = Math.round(currentAlpha * 10) / 10;
        }
        move();
    }, dragStart, dragStop);

[Source: (Lines: 1068 - 1073)][4]

    var t0 = e.originalEvent && e.originalEvent.touches && e.originalEvent.touches[0];
    var pageX = t0 && t0.pageX || e.pageX;
    var pageY = t0 && t0.pageY || e.pageY;

    var dragX = Math.max(0, Math.min(pageX - offset.left, maxWidth));
    var dragY = Math.max(0, Math.min(pageY - offset.top, maxHeight));

  [3]: https://github.com/bgrins/spectrum/blob/master/spectrum.js#L387-L395
  [4]: https://github.com/bgrins/spectrum/blob/master/spectrum.js#L1068-L1073

**Comment by bgrins** [comment]
I think you'd need to change `currentAlpha = (dragX / alphaWidth);` to something like `currentAlpha = ((alphaWidth - dragX) / alphaWidth);`.  You shouldn't need to change any of the draggable bits

**Comment by Horray** [comment]
Thanks! It works! How can I also change the selector?

Relevant Code:
[Source: (Lines: 845 - 847)][1]

    var alphaX = currentAlpha * alphaWidth;
     alphaSlideHelper.css({
        "left": (alphaX - (alphaSlideHelperWidth / 2)) + "px"
    });

[1]: [https://github.com/bgrins/spectrum/blob/master/spectrum.js#L845-L847]

**Comment by bgrins** [comment]
Looks like this was solved in #384 so you can copy code out of there
