### ISSUE TITLE
Little bug in "on change" event method?

### ISSUE THREAD

**Issue by lunanigra** [bgrins/spectrum#390]
Hello, I'm facing a strange effect using the change event method on a palette selection.

`$("#xxx").spectrum({
    flat: true,
    showInput: true,
    className: 'minuteColor',
    preferredFormat: "rgb",
    showPalette: true,
    showPaletteOnly: true,
    palette: palettes['xxx'],
    change: function(color) {
        $.ajax({
            type: "POST",
            data: JSON.stringify({ ... })
        });
    }
});`

Normally the event is fired fine. Just when clicking the orginial color no event is triggered. Ok, this may make sense as there was no "real" change. However if you trigger something via the change event it is quite important to fire the event on the original value as well.

Can you please check... Or is there another event, e.g. "on select" or "on click"?

Thanks, JC

**Comment by bgrins** [comment]
Sorry about that.  'change' events on palette selection is a known bug, #250
