### ISSUE TITLE
Translation to Czech

### ISSUE THREAD

**Issue by Laupe** [bgrins/spectrum#394]
Here I provide a Czech translation

// Spectrum Colorpicker
// Czech (cs) localization
// https://github.com/bgrins/spectrum
// author localization Pavel Dvorak <pavel@pavel-dvorak.cz>

(function ( $ ) {

    var localization = $.spectrum.localization["cs"] = {
        cancelText: "zrušit",
        chooseText: "vybrat",
        clearText: "Resetovat výměr barev",
        noColorSelectedText: "Žádná barva nebyla vybrána",
        togglePaletteMoreText: "více",
        togglePaletteLessText: "méně"
    };

    $.extend($.fn.spectrum.defaults, localization);

})( jQuery );

**Comment by bgrins** [comment]
Hi @Laupe, would you mind converting this to a pull request?

**Comment by Laupe** [comment]
Hi @bgrins pls marge ;)

**Comment by bgrins** [comment]
Done, thanks
