### ISSUE TITLE
Compatibility with mbExtruder

### ISSUE THREAD

**Issue by glemmon** [bgrins/spectrum#396]
I have a spectrum color picker in a slide out "[extruder](http://pupunzi.open-lab.com/mb-jquery-components/jquery-mb-extruder/)". The first time it slides out I can open the color pickers no problem, but once I close it and reopen it, the color picker does not open. I cannot toggle it open even from the JS console.

**Comment by bgrins** [comment]
Hi, can you come up with a test case that has steps to reproduce the problem?  Here's a template: http://jsfiddle.net/bgrins/ctkY3/

**Comment by glemmon** [comment]
Here is my test case. I think mbExtruder is not going to be compatible with jsFiddle.

https://jsfiddle.net/gordonlemmon/3xo37f42/2/

**Comment by bgrins** [comment]
> I think mbExtruder is not going to be compatible with jsFiddle.

Yeah I'm not seeing anything show up in the results of that fiddle even after pressing run.  If there's an issue with jsfiddle a test case on another site is fine

**Comment by glemmon** [comment]
http://weatherby.genetics.utah.edu/phevor2/spectrum_test/test.html

**Comment by avoliva** [comment]
The issue is that the extruder has a `z-index` value of `9999994`

Either give the extruder a lesser z-index or apply this CSS

    .sp-container {
        z-index: 9999995;
    }

**Comment by bgrins** [comment]
Thanks @avoliva
