### ISSUE TITLE
allowEmpty:true not working in Chrome

### ISSUE THREAD

**Issue by cfator** [bgrins/spectrum#398]
Possibly other browsers too.  Works in IE but in chrome the ability to choose the empty color is missing.

**Comment by avoliva** [comment]
Can you see it [here](https://bgrins.github.io/spectrum/#toc25)?

Also, are you trying to set allowEmpty after initialization? There's a PR that fixes that [here](https://github.com/bgrins/spectrum/pull/343)

**Comment by cfator** [comment]
Using those options when assigning spectrum to the inputs (after the dom is ready).  
Was able to get around that by removing the && !isInoutColorType on line 240. 

However now have a situation where the empty value is shown as black and getting the value returns black.
-charlie

**Comment by avoliva** [comment]
Ah, right. inputs of type `color` cannot be allowed to be empty. Instead of modifying the spectrum code, just give your input a type of `text`.

**Comment by cfator** [comment]
Ah thank you sir, that was what I was missing.

**Comment by bgrins** [comment]
Thanks @avoliva for responding!
