### ISSUE TITLE
color value passed into options should override a data-color value

### ISSUE THREAD

**Issue by stephen304** [bgrins/spectrum#399]
I was confused for a bit when the color picker wouldn't use the value I passed in for color, but I then discovered that it was being overridden by the value from data-color.

This should probably be noted in the documentation.

**Comment by stephen304** [comment]
Here's a JSFiddle. I pass in blue via data-color and yellow via spectrum options. It ignores yellow and uses blue from data-color instead:

https://jsfiddle.net/dL6z1efL/1/

**Comment by bgrins** [comment]
I've updated master to match the expected behavior
