### ISSUE TITLE
Firefox - jQuery dialog with modal affecting the input of the colorpicker

### ISSUE THREAD

**Issue by mslkim** [bgrins/spectrum#40]
If you place the colorpicker inside the dialog with modal enabled, you cannot click in the input box to change the color.  See fiddle http://jsfiddle.net/9bLJK/1/

**Comment by raRaRa** [comment]
I realize that this is an old issue, but I tried removing tabindex="-1" from the modal attributes and everything worked fine. I hope this is helpful for others.
