### ISSUE TITLE
PreferredFormat Overrides Alpha

### ISSUE THREAD

**Issue by bduff9** [bgrins/spectrum#400]
This might be desired behavior, but I just want to confirm.  My understanding of PreferredFormat was it was the preferential way to set the format, but able to fallback if needed (case in point, choosing name falls back to hex if there is no name available for the color chosen).  However, while I would prefer to output hex3 if possible, I would then expect it to fall back appropriately to hex, and then rgba if alpha is < 1.

Currently, on the Spectrum demo page, it does indeed fall back to full hex if needed, however it does not ever set the alpha value when I choose the available colors, but rather stays on hex3.

My application uses hex preferentially (hex3 when possible) however it is very likely someone would choose to change the alpha value so I need this fallback to work.  Is this the desired behavior and if so, is my only option to use a custom change function to try and grab the actual value instead of the hex?  Thank you!

**Comment by bduff9** [comment]
It does look like the following works fine, but again, just want to confirm that this is the best way to accomplish what I need:

```
change: function(color) {
        var a = color.getAlpha(),
            fmt;
        if (a < 1) { // If there is an alpha value, use RGBa format
          fmt = color.toRgbString();
        } else { // Otherwise, use hex3 if possible, falling back to hex
          fmt = color.toHexString(true);
        }
        this.value = fmt;
      }
```

Thanks!

**Comment by bgrins** [comment]
@bduff9 what you suggest seems right.  What's happening with preferred format is that it's passing that into the toString() call to TinyColor which is causing this condition to be false: https://github.com/bgrins/TinyColor/blob/05b205826e2497022876b69d3327751c4a72b1ad/tinycolor.js#L172.

I can't remember exactly why it's that way but I think the idea is if you say toString("name"), for instance, then it should be strict about it and return false if the color doesn't perfectly match a name.  Likewise for hex it returns the hex (ignoring the alpha) if that's been explicitly passed in.  The downside is it makes your use case more awkward.

But I think if you don't care about the intermediate state of the color in the picker UI (i.e. the format in the text input or tooltip text in palette items) then you can drop preferredFormat altogether and do what you mention in https://github.com/bgrins/spectrum/issues/400#issuecomment-195093397.

**Comment by joelstein** [comment]
Great suggestion, @bduff9! This is working perfectly for me:

```js
$(':input[type="text"].spectrum').spectrum({
  showAlpha: true,
  showInput: true,
  preferredFormat: 'hex3',
  change: function(color) {
    this.value = color.getAlpha() < 1 ? color.toRgbString() : color.toHexString(true);
  }
});
```
