### ISSUE TITLE
No way to make palette+alpha picker

### ISSUE THREAD

**Issue by Markus-13** [bgrins/spectrum#415]
Should be possible to specify via setting showPalette,showPaletteOnly,showAlpha to true, or via adding a new flag showAlphaInPalette.
- Alpha slider should be placed under the swatches.
- Width of slider should be automatically adjusted according to palette block width.
- Check mark on a color swatch should remain while rgb values of selected color are same as in swatch.

**Comment by bgrins** [comment]
I don't want to support that as a new UI configuration in the main repo (sorry, it's enough work to keep up with all the modes there are now).  Likewise with keeping a palette item selected when an alpha variation of the color is selected.
