### ISSUE TITLE
polyfill not working when dom element created after load

### ISSUE THREAD

**Issue by BHare1985** [bgrins/spectrum#418]
polyfill works fine if input exists in the DOM to begin with, but dynamically creating an input it doesn't work for IE. Any chance of having a listener that will auto apply when a jquery filter exists, similar to jquery's on body, element

**Comment by bgrins** [comment]
You could call `$.fn.spectrum.processNativeColorInputs` (or copy it's [implementation](https://github.com/bgrins/spectrum/blob/147485ed097b5ca199c914450e147ec89525f5e4/spectrum.js#L1221)) into your page whenever a new input is added.  You could detect new elements with a MutationObserver if you wanted a generic way, or if you know where the inputs are being created, you could init spectrum in that function.
