### ISSUE TITLE
hex8: rgba vs argb 

### ISSUE THREAD

**Issue by bh-ms2soft** [bgrins/spectrum#427]
For the preferred hex8 method why do you opt to use argb vs rgba order in hex bytes? : https://github.com/bgrins/spectrum/blob/master/spectrum.js#L1728 

Especially when rgba will be supported by css: https://drafts.csswg.org/css-color/#hex-notation

I'd like to see support for hex8a or something or other that goes by rgba in hex.

**Comment by bgrins** [comment]
That was originally added for microsoft's 'filter' syntax which puts the alpha in front.  I'd be happy to migrate away from that (inlining the current rgbaToHex implementation into toFilter and switching the function to use the new standard way).

Would you be interested in sending over a PR to https://github.com/bgrins/TinyColor to fix this?

**Comment by bh-ms2soft** [comment]
Glad to see this went through.
