### ISSUE TITLE
Change event isn't fired 

### ISSUE THREAD

**Issue by EpoX44** [bgrins/spectrum#443]
http://codepen.io/EpoX/pen/VjJZyz

**Following use case in the codepen:**
If I open the colorpicker and change the color via the input field to '#000000' and press ENTER the color of the div changes correctly. If I now change the color back to '#ff0000' via the input type and hit ENTER the 'change' event isn't fired. Only the color of the colorpicker changes but the object remains the same. 

Kind regards,
EpoX

**Comment by bgrins** [comment]
Hi, can you try loading the latest master version and see if the problem is resolved (https://rawgit.com/bgrins/spectrum/master/spectrum.js)?

**Comment by EpoX44** [comment]
Hey,

thanks for the fast answer. With the latest master it works, expect that I have to hear for the move instead of the change event, because the move event gets fired when hitting ENTER.
