### ISSUE TITLE
Setting up multiple color pickers in more efficient way.

### ISSUE THREAD

**Issue by vaibhavgeek** [bgrins/spectrum#524]
It would be cool instead rewriting the code again, we could setup color picker for multiple inputs at the same time. 
Something on these lines.  
`$("#cp1, #cp2 ").spectrum({`

This is just a suggestion. A better approach could be devised.

**Comment by OnlyPlanB** [comment]
You can use something like:

<input type="text" class="my_color" id="123_my_color">
<input type="text" class="my_color" id="143_my_color">
<input type="text" class="my_color" id="5343_my_color">
$(".my_color").spectrum();
 
Fiddle: http://jsfiddle.net/Sy6gU/1/

**Comment by vaibhavgeek** [comment]
In my use-case, I just wanted different palette for different color pickers but rest of the options need to be same. This is why I could not use same class selectors.  

I used jquery to set it up. Thanks for responding.
