### ISSUE TITLE
Actively maintained?

### ISSUE THREAD

**Issue by miketoth** [bgrins/spectrum#541]
hey! Was wondering if this repo is still actively maintained or if @bgrins is looking for maintainers. I'm using spectrum in a few projects and would be willing to triage+bring this repo up to date :)

**Comment by cblaze22** [comment]
I am curious too

**Comment by bgrins** [comment]
Hi @miketoth, I'm not actively maintaining this at the moment but would gladly accept some help with triaging etc! I don't have the bandwidth to review a rewrite or major refactors but bugfixes, etc should be easy to get landed.

**Comment by miketoth** [comment]
Ok, good to hear. I'll close this issue, help out where I can, and merge any of the larger refactors I need into my fork. If you do have the chance to review something larger, https://github.com/bgrins/spectrum/pull/299 would be my vote. lmk if there is anything else I can help out with

**Comment by bgrins** [comment]
Thanks @miketoth. Landing #299 seems reasonable - would you be able to give that a quick look / review?

**Comment by bgrins** [comment]
Also, what kind of larger refactors do you have / were you thinking of in your fork? I'd be open to incremental improvements here (like limiting/removing jQuery dependency, bringing tooling stack up to date, etc) - I'm mostly averse to a rewrite.

**Comment by miketoth** [comment]
> (like limiting/removing jQuery dependency, bringing tooling stack up to date, etc) 
Is exactly what I'd like to do. I've had some success bringing my fork's dependencies update to date. I'll give #299 a review -- would love to get it in :)

**Comment by seballot** [comment]
Hi @miketoth ! I tried several time to contact @bgrins, but without any success. The repo is dead of a while, and I would like also to help maintain it. Do you have a maintainer access on this repo? if yes could you give me also some access so I can test and merge some waiting PRs?

**Comment by bgrins** [comment]
@seballot as you've noted in multiple issues and emails, I'm not actively maintaining this repo right now. As such, I'm not interested in landing changes that add new options, change defaults settings, add new build tooling, etc. If you want to pursue those changes I'd recommend you do it in a fork.

The comments https://github.com/bgrins/spectrum/issues/541#issuecomment-485924115 and https://github.com/bgrins/spectrum/issues/541#issuecomment-489443314 are still pretty accurate. If there are bugfixes that are easy to review and include tests I can land them but I can't commit to merging PRs like https://github.com/bgrins/spectrum/pull/550.

**Comment by seballot** [comment]
Hi @brings, thanks for you reply !
I understand you are not actively maintaining the repo right now, but what about accepting some help to merge the pull request? If you can give me some access to the repo I can surely help.
Yes I can fork, deploy a new npm package called spectrum-colorpicker2, but it does not seems the best thing to do. But if you want I can go this way

Have a nice week end !

**Comment by bgrins** [comment]
> I understand you are not actively maintaining the repo right now, but what about accepting some help to merge the pull request?

What I said in https://github.com/bgrins/spectrum/issues/541#issuecomment-578253418:

If there are bugfixes that are easy to review and include tests I can land them but I can't commit to merging PRs like #550.
