### ISSUE TITLE
Showing color picker manually

### ISSUE THREAD

**Issue by nospor** [bgrins/spectrum#542]
Hi, is there a way to show/hide color picker manually?
eg:
colorpicker.spectrum("show")
?

**Comment by nospor** [comment]
I can see in doc, that we can do this, but this only works when you call SHOW after initialisation. When I want to call SHOW inside some onlick event, it doesnt work. Here is example of what I am talking
http://jsfiddle.net/y2ue56tf/3/

**Comment by dakruchko** [comment]
Hi
I changed your code, now this works
http://jsfiddle.net/tmxjo8nu/

**Comment by nospor** [comment]
@dakruchko  I am sure I was asking about not working function .spectrum("show"); and not how to attach spectrum to INPUT. Try next time read a little more carefully.

**Comment by dakruchko** [comment]
@nospor sorry, i believe this is what you need: http://jsfiddle.net/c4vn1r3q/
and adding onclick inside tags is not a good practice

**Comment by nospor** [comment]
@dakruchko  and this example is perfect. Ta.
