### ISSUE TITLE
This repo is currently not maintained, please go to https://github.com/seballot/spectrum instead

### ISSUE THREAD

**Issue by seballot** [bgrins/spectrum#552]
As discussed with @bgrins in #541, this repo is not currently maintained

So if you want to **access latest version** of spectrum, or if you want to **submit an issue or a pull request**, please got to

https://github.com/seballot/spectrum or https://seballot.github.io/spectrum/

![image](https://user-images.githubusercontent.com/17404254/73457977-d0688700-4374-11ea-9d04-c8d46777a02a.png)

**Comment by bgrins** [comment]
> So if you want to access latest version of spectrum, or if you want to submit an issue or a pull request, please got to

Your repo is not the "latest version of spectrum", please don't advertise it as such.

**Comment by ScotsScripts** [comment]
I'm confused. Is seballot's version the latest version or not? Or is it a different product altogether?

**Comment by bgrins** [comment]
It's a fork of this project with some different options, default styling, etc. It is not the "latest version" of this project in any way.

**Comment by seballot** [comment]
Yes you right, it's a fork, 44 commit ahead from this repo.
I also merged the latest pull request in the fork

@bgrins, I do not want in anyway to rob you the project, that's why I insisted so much to help you maintain your repo. In the fork Readme, it's also written that is has been developed by you...
I just wanted to share with the community the changes I made to the UI, which seems quite important to me

Hope you understand,
Best regards

**Comment by bgrins** [comment]
We've discussed this already in #541. I'm willing to upstream bugfixes but not large changes to the API surface or tooling. You are completely free to fork the project if you want to make those types of changes. Just don't advertise it as the "latest version" of this project in the issue tracker.

**Comment by seballot** [comment]
ok, no prob !
