### ISSUE TITLE
Providing "titles" along with palette colors

### ISSUE THREAD

**Issue by beporter** [bgrins/spectrum#60]
It would be nice to be able to provide a `title="Maroon"` attribute with each of the colors provided to `palette`. Hovering over the colors in the picker could then produce a tooltip with the _provided_ "name" of the color (instead of a hex value that mostly only means something to programmers and designers). Given that the most common use of a color picker is to make it easier for "lay people" to select a color without understand hex or HSV or RGB, it would follow that the tooltips for the colors should be more recognizable. I propose a change to the way the `palette` option is handled: Continue to accept a flat array (or multiple arrays to control rows/columns), but also allow objects with names such as:

```
palette: {
   "Maroon":"#b03060",
   "Navy":"#000080",
   "Black-ish":"#020001",
}
```

...and use the provided strings as the tooltips (if present.)

**Comment by cmrockwell** [comment]
While this is an old thread, I'm facing the same issue as OP. Would like to add title attributes to name the colors. The link seems to point to HTML. What would your current recommendation be?

**Comment by bgrins** [comment]
@cmrockwell incidentally we were just discussing what sounds like the same request today in #407.  I think the first option in https://github.com/bgrins/spectrum/issues/407#issuecomment-199330016 should work

**Comment by cmrockwell** [comment]
Yep, that works! Thanks much for the response
